language: python
python:
- 2.7
before_install:
- pip install --upgrade pip
script:
- pip install -r server/env/requirements.txt
after_success:
- BUILD_FILE=qkst-build-$TRAVIS_BUILD_NUMBER.tar.gz
- tar czvf /tmp/$BUILD_FILE . --exclude='.git'
- openssl aes-256-cbc -K $encrypted_2052dc76d87a_key -iv $encrypted_2052dc76d87a_iv
  -in server/quickstart.pem.enc -out server/quickstart.pem -d
- chmod 400 server/quickstart.pem
- echo -e "Host qkst.io\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- scp -i server/quickstart.pem /tmp/$BUILD_FILE deployer@qkst.io:/tmp
- ssh -i server/quickstart.pem deployer@qkst.io "~/deploy-qkst.sh /tmp/$BUILD_FILE >> ~/deploy-qkst.log"